//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAREASQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabla_Laboratorios
    {
        public long Id_Lab { get; set; }
        public string Laboratorio_Redes { get; set; }
        public string Laboratorio_Computo1 { get; set; }
        public string Laboratorio_Computo2 { get; set; }
    }
}
